blank_issues_enabled: true
contact_links:
  - name: Ask a question about VarCA or get support
    url: https://github.com/aryarm/varca/discussions/new
    about: Ask a question or request support for using VarCA
